config/routes.rb
ConsumerTracker::Application.routes.draw do

  get 'api_test/hello'

  get 'analytics/stats'
  get 'stats' => 'analytics#stats'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get  'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  get  'log_out' => 'sessions#destroy'

  get 'sign_up' => 'users#new'

  root 'static_pages#home'
    
  get "static_pages/home"
  get "messages/create"
  get "messages/receive"
  resources :tags do
  collection { post :export }
  end

  resources :products do
    collection { post :import }
  end

  resources :incoming_messages

  resources :outgoing_messages

  resources :senders

  resources :messages

  resources :users

  get 'faceboot' => 'static_pages#faceboot'
  get 'trinity' => 'static_pages#trinity'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
    def self.to_xls
	p = Axlsx::Package.new
	p.workbook.add_worksheet(name: 'Product Tags') do |sheet|
	    sheet.add_row ["Tag", "Date Generated"]

	    all.each do |tag|
		sheet.add_row [tag.value, tag.created_at]
	    end
	end

	filename = '/tmp/' + ('a'..'z').to_a.sample + ('0'..'9').to_a.sample + '.xls'
	p.serialize(filename)
	filename
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include SessionsHelper

  before_action { make_user_log_in_first unless logged_in? }
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
#    params[:q][:created_at_lt] = convertDateToStd(params[:q][:created_at_lt])
#    params[:q][:created_at_gt] = convertDateToStd(params[:q][:created_at_gt])
   @q = Tag.ransack(params[:q])

   respond_to do |format|
       format.html { @tags = @q.result(distinct: true).page params[:page] }
       format.xls do
	    @tags = @q.result(distinct: true)
	    send_file @tags.to_xls
       end
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
#    @tag = Tag.new(tag_params)

#    respond_to do |format|
#      if @tag.save
#        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
#        format.json { render action: 'show', status: :created, location: @tag }
#      else
#        format.html { render action: 'new' }
#        format.json { render json: @tag.errors, status: :unprocessable_entity }
#      end
#    end

    number_of_tags = params[:number_of_tags].to_i
    prefix = params[:prefix]
    minimum = params[:minimum].to_i
    default_min = 1000000000
    maximum = params[:maximum].to_i
    default_max = 9999999999

    if maximum < minimum then
	minimum = default_min
	maximum = default_max
    end

    tag_ids = []

    tag_generator = Random.new

    1.upto(number_of_tags).each do
	value = tag_generator.rand(maximum - minimum) + minimum	
	value = prefix + value.to_s
	@tag = Tag.new(value: value)

    	if @tag.save! then
	    tag_ids << @tag.id
	end
    end

    @q = Tag.where(id: tag_ids).ransack(params[:q])
#@tags = Tag.where(id: tag_ids).page params[:page]
    @tags = @q.result(distinct: true).page params[:page]
    render 'index'
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  def export
    @tags = Tag.where(id: params[:tag_ids])
    send_file @tags.to_xls
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:value)
    end

    def convertDateToStd( date_string )
	date_string.to_s.split('/').reverse.join('-')
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @tag, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :value, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :value, :class => 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  tags_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/tags/edit.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tags/index.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= paginate @tags %>
<%= search_form_for @q, html: {class: 'form-inline'} do |f| %>
   <%= f.label :value_start %>
   <%= f.search_field :value_start, class: 'form-control' %>
	created between 
   <%= f.date_field :created_at_gt, class: 'form-control' %>
	and
   <%= f.date_field :created_at_lt, class: 'form-control' %>
   <%= f.submit 'filter', class: 'btn btn-lg btn-info' %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
	<th>
	    <span class="pull-right">
		Export
		<span class="glyphicon glyphicon-export"></span>
	    </span>
	</th>
	<td>
	    <span class="pull-right">
		<%= link_to 'Excel', tags_path + '.xls', class: 'btn btn-info btn-lg' %>
	    </span>
	</td>
    </tr>
    <tr>
      <th><%= check_box_tag 'all_tags'%></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
      <td>
        <%= check_box_tag 'tag_ids[]', tag.id %>
	</td>
        <td><%= tag.id %></td>
          <td><%= tag.value %></td>
        <td><%=l tag.created_at, format: :long %></td>
        <td>
          <%= link_to tag_path(tag), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_tag_path(tag), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to tag_path(tag), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tag_path,
            :class => 'btn btn-primary' %>

app/views/tags/new.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%#=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%#= render :partial => 'form' %>
<div class="container">
<%= form_tag( {controller: "tags", action: "create"}, class: 'form-inline' ) do  %>
    <div class="input-group col-md-2">
       <%= number_field_tag 'number_of_tags', '1', min: 1, max: 1000 , class: 'form-control'%>		
       <span class="input-group-addon">tags</span>
    </div>
    <div class="input-group col-md-2">
       <span class="input-group-addon">Prefix</span>
       <%= text_field_tag 'prefix', '', maxlength: 3, class: 'form-control', placeholder: 'Enter a prefix'%>		
    </div>
    <span>
	  &nbsp;<strong>Range:</strong>&nbsp;
    </span>
    <div class="input-group col-md-2">
       <span class="input-group-addon" >Between</span>
       <%= number_field_tag 'minimum', '0', min: 1, class: 'form-control' %>			
    </div>
    <div class="input-group col-md-2">
       <span class="input-group-addon" >and</span>
       <%= number_field_tag 'maximum', '10', min: 10, class: 'form-control' %>			
    </div>

    <br />

    <div class="input-group" style="padding-top: 15px">
	<%= submit_tag 'Generate!', class: 'btn btn-lg btn-info' %>
    </div>
<% end %>
</div>

app/views/tags/show.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:value) %></dt>
      <dd><pre class="prettyprint"><%= @tag.value %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tags_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tag_path(@tag), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tag_path(@tag),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>