config/routes.rb
ConsumerTracker::Application.routes.draw do

  get 'api_test/hello'

  get 'analytics/stats'
  get 'stats' => 'analytics#stats'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get  'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  get  'log_out' => 'sessions#destroy'

  get 'sign_up' => 'users#new'

  root 'static_pages#home'
    
  get "static_pages/home"
  get "messages/create"
  get "messages/receive"
  resources :tags do
  collection { post :export }
  end

  resources :products do
    collection { post :import }
  end

  resources :incoming_messages

  resources :outgoing_messages

  resources :senders

  resources :messages

  resources :users

  get 'faceboot' => 'static_pages#faceboot'
  get 'trinity' => 'static_pages#trinity'

end

app/models/outgoing_message.rb
class OutgoingMessage < ActiveRecord::Base
end

app/controllers/outgoing_messages_controller.rb
class OutgoingMessagesController < ApplicationController
  before_action :set_outgoing_message, only: [:show, :edit, :update, :destroy]

  # GET /outgoing_messages
  # GET /outgoing_messages.json
  def index
    @outgoing_messages = OutgoingMessage.all
  end

  # GET /outgoing_messages/1
  # GET /outgoing_messages/1.json
  def show
  end

  # GET /outgoing_messages/new
  def new
    @outgoing_message = OutgoingMessage.new
  end

  # GET /outgoing_messages/1/edit
  def edit
  end

  # POST /outgoing_messages
  # POST /outgoing_messages.json
  def create
    @outgoing_message = OutgoingMessage.new(outgoing_message_params)

    respond_to do |format|
      if @outgoing_message.save
        format.html { redirect_to @outgoing_message, notice: 'Outgoing message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @outgoing_message }
      else
        format.html { render action: 'new' }
        format.json { render json: @outgoing_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outgoing_messages/1
  # PATCH/PUT /outgoing_messages/1.json
  def update
    respond_to do |format|
      if @outgoing_message.update(outgoing_message_params)
        format.html { redirect_to @outgoing_message, notice: 'Outgoing message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @outgoing_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outgoing_messages/1
  # DELETE /outgoing_messages/1.json
  def destroy
    @outgoing_message.destroy
    respond_to do |format|
      format.html { redirect_to outgoing_messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outgoing_message
      @outgoing_message = OutgoingMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outgoing_message_params
      params.require(:outgoing_message).permit(:recipient, :message)
    end
end

app/helpers/outgoing_messages_helper.rb
module OutgoingMessagesHelper
end

app/views/outgoing_messages/_form.html.erb
<%= form_for @outgoing_message, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :recipient, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :recipient, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :message, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :message, :class => 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  outgoing_messages_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/outgoing_messages/edit.html.erb
<%- model_class = OutgoingMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/outgoing_messages/index.html.erb
<%- model_class = OutgoingMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:recipient) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @outgoing_messages.each do |outgoing_message| %>
      <tr>
        <td><%= outgoing_message.id %></td>
          <td><%= outgoing_message.recipient %></td>
          <td><%= outgoing_message.message %></td>
        <td><%=l outgoing_message.created_at, format: :long %></td>
        <td>
          <%= link_to outgoing_message_path(outgoing_message), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_outgoing_message_path(outgoing_message), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to outgoing_message_path(outgoing_message), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_outgoing_message_path,
            :class => 'btn btn-primary' %>

app/views/outgoing_messages/new.html.erb
<%- model_class = OutgoingMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/outgoing_messages/show.html.erb
<%- model_class = OutgoingMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:recipient) %></dt>
      <dd><pre class="prettyprint"><%= @outgoing_message.recipient %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:message) %></dt>
      <dd><pre class="prettyprint"><%= @outgoing_message.message %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              outgoing_messages_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_outgoing_message_path(@outgoing_message), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              outgoing_message_path(@outgoing_message),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>