config/routes.rb
ConsumerTracker::Application.routes.draw do

  get 'api_test/hello'

  get 'analytics/stats'
  get 'stats' => 'analytics#stats'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get  'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  get  'log_out' => 'sessions#destroy'

  get 'sign_up' => 'users#new'

  root 'static_pages#home'
    
  get "static_pages/home"
  get "messages/create"
  get "messages/receive"
  resources :tags do
  collection { post :export }
  end

  resources :products do
    collection { post :import }
  end

  resources :incoming_messages

  resources :outgoing_messages

  resources :senders

  resources :messages

  resources :users

  get 'faceboot' => 'static_pages#faceboot'
  get 'trinity' => 'static_pages#trinity'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "ConsumerTracker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
       <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	  <%= link_to 'Consumer Tracker', root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li <%=  current_page?(controller: 'products') ? 'class=active' : '' %> >
		<%= link_to "Products", products_path %>
	    </li>
	    <li <%= current_page?('/stats' ) ? 'class=active' : '' %> >
	    	<%= link_to "Statistics", stats_path %>
	    </li>
          </ul>

	  <ul class="nav navbar-nav navbar-right">
	    <li>
		<%=
		    link_to_if logged_in?, current_user.nil? ? '' : current_user.username, nil, { class: 'navbar-brand' } do
			link_to 'Log in', log_in_path
		    end
		%>
	    </li>
	    <li>
		<%= 
		    link_to_if logged_in?, 'Log out', log_out_path do
			''
		    end
		%>
	    </li>
	  </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    

    <div class="container">
      <div class="row">
        <div >
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Consumer Tracker 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>